/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ResultsRouteImport } from './routes/results'
import { Route as RoutineRouteImport } from './routes/routine'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as ApiSkinAnalysisRouteImport } from './routes/api/skin-analysis'
import { Route as ApiSkinDirectionRouteImport } from './routes/api/skin-direction'
import { Route as ApiSkinStrategyRouteImport } from './routes/api/skin-strategy'
import { Route as HistoryAnalysisIdRouteImport } from './routes/history.$analysisId'
import { Route as IngredientsIndexRouteImport } from './routes/ingredients.index'
import { Route as IngredientsIngredientIdRouteImport } from './routes/ingredients.$ingredientId'
import { Route as ScanIndexRouteImport } from './routes/scan.index'
import { Route as ScanCheckInRouteImport } from './routes/scan.check-in'
import { Route as ShelfIndexRouteImport } from './routes/shelf.index'
import { Route as ShelfProductIdRouteImport } from './routes/shelf.$productId'
import { Route as ShelfAddRouteImport } from './routes/shelf.add'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsRoute = ResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => rootRouteImport,
} as any)
const RoutineRoute = RoutineRouteImport.update({
  id: '/routine',
  path: '/routine',
  getParentRoute: () => rootRouteImport,
} as any)
const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiSkinAnalysisRoute = ApiSkinAnalysisRouteImport.update({
  id: '/api/skin-analysis',
  path: '/api/skin-analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSkinDirectionRoute = ApiSkinDirectionRouteImport.update({
  id: '/api/skin-direction',
  path: '/api/skin-direction',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSkinStrategyRoute = ApiSkinStrategyRouteImport.update({
  id: '/api/skin-strategy',
  path: '/api/skin-strategy',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryAnalysisIdRoute = HistoryAnalysisIdRouteImport.update({
  id: '/history/$analysisId',
  path: '/history/$analysisId',
  getParentRoute: () => rootRouteImport,
} as any)
const IngredientsIndexRoute = IngredientsIndexRouteImport.update({
  id: '/ingredients/',
  path: '/ingredients/',
  getParentRoute: () => rootRouteImport,
} as any)
const IngredientsIngredientIdRoute = IngredientsIngredientIdRouteImport.update({
  id: '/ingredients/$ingredientId',
  path: '/ingredients/$ingredientId',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanIndexRoute = ScanIndexRouteImport.update({
  id: '/scan/',
  path: '/scan/',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanCheckInRoute = ScanCheckInRouteImport.update({
  id: '/scan/check-in',
  path: '/scan/check-in',
  getParentRoute: () => rootRouteImport,
} as any)
const ShelfIndexRoute = ShelfIndexRouteImport.update({
  id: '/shelf/',
  path: '/shelf/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShelfProductIdRoute = ShelfProductIdRouteImport.update({
  id: '/shelf/$productId',
  path: '/shelf/$productId',
  getParentRoute: () => rootRouteImport,
} as any)
const ShelfAddRoute = ShelfAddRouteImport.update({
  id: '/shelf/add',
  path: '/shelf/add',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/insights': typeof InsightsRoute
  '/mcp': typeof McpRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/results': typeof ResultsRoute
  '/routine': typeof RoutineRoute
  '/welcome': typeof WelcomeRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/api/skin-analysis': typeof ApiSkinAnalysisRoute
  '/api/skin-direction': typeof ApiSkinDirectionRoute
  '/api/skin-strategy': typeof ApiSkinStrategyRoute
  '/history/$analysisId': typeof HistoryAnalysisIdRoute
  '/ingredients/$ingredientId': typeof IngredientsIngredientIdRoute
  '/scan/check-in': typeof ScanCheckInRoute
  '/shelf/$productId': typeof ShelfProductIdRoute
  '/shelf/add': typeof ShelfAddRoute
  '/ingredients/': typeof IngredientsIndexRoute
  '/scan/': typeof ScanIndexRoute
  '/shelf/': typeof ShelfIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/insights': typeof InsightsRoute
  '/mcp': typeof McpRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/results': typeof ResultsRoute
  '/routine': typeof RoutineRoute
  '/welcome': typeof WelcomeRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/api/skin-analysis': typeof ApiSkinAnalysisRoute
  '/api/skin-direction': typeof ApiSkinDirectionRoute
  '/api/skin-strategy': typeof ApiSkinStrategyRoute
  '/history/$analysisId': typeof HistoryAnalysisIdRoute
  '/ingredients/$ingredientId': typeof IngredientsIngredientIdRoute
  '/scan/check-in': typeof ScanCheckInRoute
  '/shelf/$productId': typeof ShelfProductIdRoute
  '/shelf/add': typeof ShelfAddRoute
  '/ingredients': typeof IngredientsIndexRoute
  '/scan': typeof ScanIndexRoute
  '/shelf': typeof ShelfIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/insights': typeof InsightsRoute
  '/mcp': typeof McpRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/results': typeof ResultsRoute
  '/routine': typeof RoutineRoute
  '/welcome': typeof WelcomeRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/api/skin-analysis': typeof ApiSkinAnalysisRoute
  '/api/skin-direction': typeof ApiSkinDirectionRoute
  '/api/skin-strategy': typeof ApiSkinStrategyRoute
  '/history/$analysisId': typeof HistoryAnalysisIdRoute
  '/ingredients/$ingredientId': typeof IngredientsIngredientIdRoute
  '/scan/check-in': typeof ScanCheckInRoute
  '/shelf/$productId': typeof ShelfProductIdRoute
  '/shelf/add': typeof ShelfAddRoute
  '/ingredients/': typeof IngredientsIndexRoute
  '/scan/': typeof ScanIndexRoute
  '/shelf/': typeof ShelfIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/insights'
    | '/mcp'
    | '/onboarding'
    | '/profile'
    | '/results'
    | '/routine'
    | '/welcome'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/api/skin-analysis'
    | '/api/skin-direction'
    | '/api/skin-strategy'
    | '/history/$analysisId'
    | '/ingredients/$ingredientId'
    | '/scan/check-in'
    | '/shelf/$productId'
    | '/shelf/add'
    | '/ingredients/'
    | '/scan/'
    | '/shelf/'
    | '/.mcp/invoke-tool/$tool'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/insights'
    | '/mcp'
    | '/onboarding'
    | '/profile'
    | '/results'
    | '/routine'
    | '/welcome'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/api/skin-analysis'
    | '/api/skin-direction'
    | '/api/skin-strategy'
    | '/history/$analysisId'
    | '/ingredients/$ingredientId'
    | '/scan/check-in'
    | '/shelf/$productId'
    | '/shelf/add'
    | '/ingredients'
    | '/scan'
    | '/shelf'
    | '/.mcp/invoke-tool/$tool'
  id:
    | '__root__'
    | '/'
    | '/insights'
    | '/mcp'
    | '/onboarding'
    | '/profile'
    | '/results'
    | '/routine'
    | '/welcome'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/api/skin-analysis'
    | '/api/skin-direction'
    | '/api/skin-strategy'
    | '/history/$analysisId'
    | '/ingredients/$ingredientId'
    | '/scan/check-in'
    | '/shelf/$productId'
    | '/shelf/add'
    | '/ingredients/'
    | '/scan/'
    | '/shelf/'
    | '/.mcp/invoke-tool/$tool'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  InsightsRoute: typeof InsightsRoute
  McpRoute: typeof McpRoute
  OnboardingRoute: typeof OnboardingRoute
  ProfileRoute: typeof ProfileRoute
  ResultsRoute: typeof ResultsRoute
  RoutineRoute: typeof RoutineRoute
  WelcomeRoute: typeof WelcomeRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  ApiSkinAnalysisRoute: typeof ApiSkinAnalysisRoute
  ApiSkinDirectionRoute: typeof ApiSkinDirectionRoute
  ApiSkinStrategyRoute: typeof ApiSkinStrategyRoute
  HistoryAnalysisIdRoute: typeof HistoryAnalysisIdRoute
  IngredientsIngredientIdRoute: typeof IngredientsIngredientIdRoute
  ScanCheckInRoute: typeof ScanCheckInRoute
  ShelfProductIdRoute: typeof ShelfProductIdRoute
  ShelfAddRoute: typeof ShelfAddRoute
  IngredientsIndexRoute: typeof IngredientsIndexRoute
  ScanIndexRoute: typeof ScanIndexRoute
  ShelfIndexRoute: typeof ShelfIndexRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results': {
      id: '/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof ResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/routine': {
      id: '/routine'
      path: '/routine'
      fullPath: '/routine'
      preLoaderRoute: typeof RoutineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/skin-analysis': {
      id: '/api/skin-analysis'
      path: '/api/skin-analysis'
      fullPath: '/api/skin-analysis'
      preLoaderRoute: typeof ApiSkinAnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/skin-direction': {
      id: '/api/skin-direction'
      path: '/api/skin-direction'
      fullPath: '/api/skin-direction'
      preLoaderRoute: typeof ApiSkinDirectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/skin-strategy': {
      id: '/api/skin-strategy'
      path: '/api/skin-strategy'
      fullPath: '/api/skin-strategy'
      preLoaderRoute: typeof ApiSkinStrategyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history/$analysisId': {
      id: '/history/$analysisId'
      path: '/history/$analysisId'
      fullPath: '/history/$analysisId'
      preLoaderRoute: typeof HistoryAnalysisIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ingredients/': {
      id: '/ingredients/'
      path: '/ingredients'
      fullPath: '/ingredients/'
      preLoaderRoute: typeof IngredientsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ingredients/$ingredientId': {
      id: '/ingredients/$ingredientId'
      path: '/ingredients/$ingredientId'
      fullPath: '/ingredients/$ingredientId'
      preLoaderRoute: typeof IngredientsIngredientIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan/': {
      id: '/scan/'
      path: '/scan'
      fullPath: '/scan/'
      preLoaderRoute: typeof ScanIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan/check-in': {
      id: '/scan/check-in'
      path: '/scan/check-in'
      fullPath: '/scan/check-in'
      preLoaderRoute: typeof ScanCheckInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shelf/': {
      id: '/shelf/'
      path: '/shelf'
      fullPath: '/shelf/'
      preLoaderRoute: typeof ShelfIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shelf/$productId': {
      id: '/shelf/$productId'
      path: '/shelf/$productId'
      fullPath: '/shelf/$productId'
      preLoaderRoute: typeof ShelfProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shelf/add': {
      id: '/shelf/add'
      path: '/shelf/add'
      fullPath: '/shelf/add'
      preLoaderRoute: typeof ShelfAddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  InsightsRoute: InsightsRoute,
  McpRoute: McpRoute,
  OnboardingRoute: OnboardingRoute,
  ProfileRoute: ProfileRoute,
  ResultsRoute: ResultsRoute,
  RoutineRoute: RoutineRoute,
  WelcomeRoute: WelcomeRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  ApiSkinAnalysisRoute: ApiSkinAnalysisRoute,
  ApiSkinDirectionRoute: ApiSkinDirectionRoute,
  ApiSkinStrategyRoute: ApiSkinStrategyRoute,
  HistoryAnalysisIdRoute: HistoryAnalysisIdRoute,
  IngredientsIngredientIdRoute: IngredientsIngredientIdRoute,
  ScanCheckInRoute: ScanCheckInRoute,
  ShelfProductIdRoute: ShelfProductIdRoute,
  ShelfAddRoute: ShelfAddRoute,
  IngredientsIndexRoute: IngredientsIndexRoute,
  ScanIndexRoute: ScanIndexRoute,
  ShelfIndexRoute: ShelfIndexRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
